apiVersion: v1
kind: Service
metadata:
  name: house-price-serving-service
  labels:   # This was the issue
    app: house-price-serving
spec:
  selector:
    app: house-price-serving    # select pods with this label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000