name: CI_CT_CD_DriftDetection_Canary Pipeline

on:
  push:
    paths:
      - "src/**"
      - "data/**"
      - "params.yml"
      - "requirements.txt"
  pull_request:
  workflow_dispatch:

jobs:
  Continuous-Training:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install DVC + deps
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install
          pip install -r requirements.txt
          pip install dvc
      - name: Configure DVC remote
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user $DAGSHUB_USERNAME
          dvc remote modify origin --local password $DAGSHUB_TOKEN
      - name: Reproduce DVC pipeline (CT)
        run: |
          dvc repro --no-run-cache
      - name: Push updated DVC artifacts (model, processed data, metrics)
        run: |
          dvc push
      - name: Upload model as GitHub artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/model.pkl

  Drift-Detection:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Drift Detection
        run: |
          python3 src/drift_check.py

  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.fastapi
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/house-price-serving:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/house-price-serving:${{ github.sha }}

  Continuous-Delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Update image tag
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/house-price-serving:${{ github.sha }}|" k8s_manifests/deployment-v1.yml
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s_manifests/deployment-v1.yml
          git commit -m "CD: Update image tag to ${{ github.sha }}"
          git push